apiVersion: v1
kind: Service
metadata:
  labels:
    app: game
  name: game
  namespace: demo
spec:
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 31836
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: game
  sessionAffinity: None
  type: LoadBalancer
